apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: devops-website-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: devops-website-img-repo
  policy:
    semver:
      range: x.x.x
