apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: devops-website-img-repo
  namespace: flux-system
spec:
  image: registry.gitlab.com/nersent/cloud/devops-zaliczenie
  interval: 1m0s
  secretRef:
    name: regcred
