name: Jenkins Pipeline via apt
on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  ephemeral-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      - name: Install Jenkins from apt
        run: |
          # Import Jenkins GPG key
          curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key \
            | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
          # Add Jenkins repo
          echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" \
            | sudo tee /etc/apt/sources.list.d/jenkins.list
          # Update & install Jenkins
          sudo apt-get update
          sudo apt-get install -y jenkins
          # Start Jenkins
          sudo systemctl start jenkins
          sleep 30
          sudo systemctl status jenkins --no-pager || true

      - name: Install Pipeline plugins
        run: |
          # Jenkins must be running
          # Grab the initial admin password so we can authenticate
          PASS="$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)"
          # Download Jenkins CLI to manage plugins:
          curl -sSfL http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar -o jenkins-cli.jar

          # The “workflow-aggregator” plugin essentially brings in the main pipeline plugins:
          java -jar jenkins-cli.jar \
            -auth "admin:${PASS}" \
            -s http://127.0.0.1:8080/ install-plugin workflow-aggregator

          # Optionally: install other pipeline plugins if you need them
          # java -jar jenkins-cli.jar -auth admin:$PASS -s http://127.0.0.1:8080/ install-plugin workflow-cps ...

          # We must restart Jenkins so the plugin can load:
          java -jar jenkins-cli.jar \
            -auth "admin:${PASS}" \
            -s http://127.0.0.1:8080/ safe-restart

          # Wait a bit for Jenkins to come back:
          sleep 60

      - name: Create Jenkins job using .github/jenkins_job.xml
        run: |
          PASS="$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)"
          curl -sSfL http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar -o jenkins-cli.jar
          java -jar jenkins-cli.jar -auth "admin:${PASS}" -s http://127.0.0.1:8080/ create-job MyPipeline < .github/jenkins_job.xml

      - name: Build the Jenkins pipeline
        run: |
          PASS="$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)"
          java -jar jenkins-cli.jar -auth "admin:${PASS}" -s http://127.0.0.1:8080/ build MyPipeline -f -v
