name: Jenkins Pipeline via apt

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  ephemeral-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      - name: Import Jenkins GPG key & repo, then install Jenkins
        run: |
          # Acquire and place the Jenkins GPG key
          curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key \
            | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
          # Add Jenkins stable repo
          echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" \
            | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
          # Update and install
          sudo apt-get update
          sudo apt-get install -y jenkins

      - name: Start Jenkins
        run: |
          sudo systemctl start jenkins
          # Give Jenkins time to initialize
          sleep 30
          # Print status (non-fatal if it fails)
          sudo systemctl status jenkins --no-pager || true

      - name: Create Jenkins job from .github/jenkins_job.xml
        run: |
          # Grab auto-generated admin password
          PASS="$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)"
          # Download Jenkins CLI locally
          curl -sSfL http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar -o jenkins-cli.jar
          # Create the job "MyPipeline"
          java -jar jenkins-cli.jar \
            -auth "admin:${PASS}" \
            -s http://127.0.0.1:8080/ create-job MyPipeline < .github/jenkins_job.xml

      - name: Build the Jenkins pipeline
        run: |
          PASS="$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)"
          java -jar jenkins-cli.jar \
            -auth "admin:${PASS}" \
            -s http://127.0.0.1:8080/ build MyPipeline -f -v
