name: Jenkins via apt

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  install-and-run-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      - name: Import Jenkins GPG key and add Jenkins repo
        run: |
          # Download and place the Jenkins GPG key in /usr/share/keyrings
          curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key \
            | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

          # Add Jenkins stable repository referencing its key
          echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" \
            | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

          # Apt update and install Jenkins
          sudo apt-get update
          sudo apt-get install -y jenkins

      - name: Start Jenkins
        run: |
          sudo systemctl start jenkins
          # Wait for Jenkins to come up
          sleep 30
          # Print Jenkins status
          sudo systemctl status jenkins --no-pager || true

      - name: Check Jenkins
        run: |
          curl -I http://localhost:8080
